// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: server/translate.proto
// Protobuf C++ Version: 5.29.5

#include "server/translate.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace translate {

inline constexpr TranslateResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TranslateResponse::TranslateResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TranslateResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TranslateResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TranslateResponseDefaultTypeInternal() {}
  union {
    TranslateResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TranslateResponseDefaultTypeInternal _TranslateResponse_default_instance_;

inline constexpr TranslateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_jp_to_en_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TranslateRequest::TranslateRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TranslateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TranslateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TranslateRequestDefaultTypeInternal() {}
  union {
    TranslateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TranslateRequestDefaultTypeInternal _TranslateRequest_default_instance_;
}  // namespace translate
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_server_2ftranslate_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_server_2ftranslate_2eproto = nullptr;
const ::uint32_t
    TableStruct_server_2ftranslate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::translate::TranslateRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::translate::TranslateRequest, _impl_.content_),
        PROTOBUF_FIELD_OFFSET(::translate::TranslateRequest, _impl_.is_jp_to_en_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::translate::TranslateResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::translate::TranslateResponse, _impl_.content_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::translate::TranslateRequest)},
        {10, -1, -1, sizeof(::translate::TranslateResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::translate::_TranslateRequest_default_instance_._instance,
    &::translate::_TranslateResponse_default_instance_._instance,
};
const char descriptor_table_protodef_server_2ftranslate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026server/translate.proto\022\ttranslate\032\033goo"
    "gle/protobuf/empty.proto\"8\n\020TranslateReq"
    "uest\022\017\n\007content\030\001 \001(\t\022\023\n\013is_jp_to_en\030\002 \001"
    "(\010\"$\n\021TranslateResponse\022\017\n\007content\030\001 \001(\t"
    "2\332\001\n\020TranslateService\022=\n\tLoadModel\022\026.goo"
    "gle.protobuf.Empty\032\026.google.protobuf.Emp"
    "ty\"\000\022=\n\tFreeModel\022\026.google.protobuf.Empt"
    "y\032\026.google.protobuf.Empty\"\000\022H\n\tTranslate"
    "\022\033.translate.TranslateRequest\032\034.translat"
    "e.TranslateResponse\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_server_2ftranslate_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_server_2ftranslate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_server_2ftranslate_2eproto = {
    false,
    false,
    389,
    descriptor_table_protodef_server_2ftranslate_2eproto,
    "server/translate.proto",
    &descriptor_table_server_2ftranslate_2eproto_once,
    descriptor_table_server_2ftranslate_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_server_2ftranslate_2eproto::offsets,
    file_level_enum_descriptors_server_2ftranslate_2eproto,
    file_level_service_descriptors_server_2ftranslate_2eproto,
};
namespace translate {
// ===================================================================

class TranslateRequest::_Internal {
 public:
};

TranslateRequest::TranslateRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:translate.TranslateRequest)
}
inline PROTOBUF_NDEBUG_INLINE TranslateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::translate::TranslateRequest& from_msg)
      : content_(arena, from.content_),
        _cached_size_{0} {}

TranslateRequest::TranslateRequest(
    ::google::protobuf::Arena* arena,
    const TranslateRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TranslateRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.is_jp_to_en_ = from._impl_.is_jp_to_en_;

  // @@protoc_insertion_point(copy_constructor:translate.TranslateRequest)
}
inline PROTOBUF_NDEBUG_INLINE TranslateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        _cached_size_{0} {}

inline void TranslateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_jp_to_en_ = {};
}
TranslateRequest::~TranslateRequest() {
  // @@protoc_insertion_point(destructor:translate.TranslateRequest)
  SharedDtor(*this);
}
inline void TranslateRequest::SharedDtor(MessageLite& self) {
  TranslateRequest& this_ = static_cast<TranslateRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TranslateRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TranslateRequest(arena);
}
constexpr auto TranslateRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TranslateRequest),
                                            alignof(TranslateRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TranslateRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TranslateRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TranslateRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TranslateRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TranslateRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TranslateRequest>(), &TranslateRequest::ByteSizeLong,
            &TranslateRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_._cached_size_),
        false,
    },
    &TranslateRequest::kDescriptorMethods,
    &descriptor_table_server_2ftranslate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TranslateRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2> TranslateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::translate::TranslateRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool is_jp_to_en = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TranslateRequest, _impl_.is_jp_to_en_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_.is_jp_to_en_)}},
    // string content = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string content = 1;
    {PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool is_jp_to_en = 2;
    {PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_.is_jp_to_en_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\32\7\0\0\0\0\0\0"
    "translate.TranslateRequest"
    "content"
  }},
};

PROTOBUF_NOINLINE void TranslateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:translate.TranslateRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _impl_.is_jp_to_en_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TranslateRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TranslateRequest& this_ = static_cast<const TranslateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TranslateRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TranslateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:translate.TranslateRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string content = 1;
          if (!this_._internal_content().empty()) {
            const std::string& _s = this_._internal_content();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "translate.TranslateRequest.content");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool is_jp_to_en = 2;
          if (this_._internal_is_jp_to_en() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_is_jp_to_en(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:translate.TranslateRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TranslateRequest::ByteSizeLong(const MessageLite& base) {
          const TranslateRequest& this_ = static_cast<const TranslateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TranslateRequest::ByteSizeLong() const {
          const TranslateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:translate.TranslateRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string content = 1;
            if (!this_._internal_content().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_content());
            }
            // bool is_jp_to_en = 2;
            if (this_._internal_is_jp_to_en() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TranslateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TranslateRequest*>(&to_msg);
  auto& from = static_cast<const TranslateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:translate.TranslateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_is_jp_to_en() != 0) {
    _this->_impl_.is_jp_to_en_ = from._impl_.is_jp_to_en_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TranslateRequest::CopyFrom(const TranslateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:translate.TranslateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TranslateRequest::InternalSwap(TranslateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
        swap(_impl_.is_jp_to_en_, other->_impl_.is_jp_to_en_);
}

::google::protobuf::Metadata TranslateRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TranslateResponse::_Internal {
 public:
};

TranslateResponse::TranslateResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:translate.TranslateResponse)
}
inline PROTOBUF_NDEBUG_INLINE TranslateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::translate::TranslateResponse& from_msg)
      : content_(arena, from.content_),
        _cached_size_{0} {}

TranslateResponse::TranslateResponse(
    ::google::protobuf::Arena* arena,
    const TranslateResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TranslateResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:translate.TranslateResponse)
}
inline PROTOBUF_NDEBUG_INLINE TranslateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        _cached_size_{0} {}

inline void TranslateResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TranslateResponse::~TranslateResponse() {
  // @@protoc_insertion_point(destructor:translate.TranslateResponse)
  SharedDtor(*this);
}
inline void TranslateResponse::SharedDtor(MessageLite& self) {
  TranslateResponse& this_ = static_cast<TranslateResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TranslateResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TranslateResponse(arena);
}
constexpr auto TranslateResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TranslateResponse),
                                            alignof(TranslateResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TranslateResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TranslateResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TranslateResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TranslateResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TranslateResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TranslateResponse>(), &TranslateResponse::ByteSizeLong,
            &TranslateResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TranslateResponse, _impl_._cached_size_),
        false,
    },
    &TranslateResponse::kDescriptorMethods,
    &descriptor_table_server_2ftranslate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TranslateResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> TranslateResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::translate::TranslateResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string content = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TranslateResponse, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string content = 1;
    {PROTOBUF_FIELD_OFFSET(TranslateResponse, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\7\0\0\0\0\0\0"
    "translate.TranslateResponse"
    "content"
  }},
};

PROTOBUF_NOINLINE void TranslateResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:translate.TranslateResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TranslateResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TranslateResponse& this_ = static_cast<const TranslateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TranslateResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TranslateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:translate.TranslateResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string content = 1;
          if (!this_._internal_content().empty()) {
            const std::string& _s = this_._internal_content();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "translate.TranslateResponse.content");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:translate.TranslateResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TranslateResponse::ByteSizeLong(const MessageLite& base) {
          const TranslateResponse& this_ = static_cast<const TranslateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TranslateResponse::ByteSizeLong() const {
          const TranslateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:translate.TranslateResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string content = 1;
            if (!this_._internal_content().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_content());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TranslateResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TranslateResponse*>(&to_msg);
  auto& from = static_cast<const TranslateResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:translate.TranslateResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TranslateResponse::CopyFrom(const TranslateResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:translate.TranslateResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TranslateResponse::InternalSwap(TranslateResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
}

::google::protobuf::Metadata TranslateResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace translate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_server_2ftranslate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
