// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server/translate.proto

#include "server/translate.pb.h"
#include "server/translate.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace translate {

static const char* TranslateService_method_names[] = {
  "/translate.TranslateService/LoadModel",
  "/translate.TranslateService/Translate",
};

std::unique_ptr< TranslateService::Stub> TranslateService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TranslateService::Stub> stub(new TranslateService::Stub(channel, options));
  return stub;
}

TranslateService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_LoadModel_(TranslateService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Translate_(TranslateService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TranslateService::Stub::LoadModel(::grpc::ClientContext* context, const ::translate::Void& request, ::translate::Void* response) {
  return ::grpc::internal::BlockingUnaryCall< ::translate::Void, ::translate::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LoadModel_, context, request, response);
}

void TranslateService::Stub::async::LoadModel(::grpc::ClientContext* context, const ::translate::Void* request, ::translate::Void* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::translate::Void, ::translate::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadModel_, context, request, response, std::move(f));
}

void TranslateService::Stub::async::LoadModel(::grpc::ClientContext* context, const ::translate::Void* request, ::translate::Void* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::translate::Void>* TranslateService::Stub::PrepareAsyncLoadModelRaw(::grpc::ClientContext* context, const ::translate::Void& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::translate::Void, ::translate::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LoadModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::translate::Void>* TranslateService::Stub::AsyncLoadModelRaw(::grpc::ClientContext* context, const ::translate::Void& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoadModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TranslateService::Stub::Translate(::grpc::ClientContext* context, const ::translate::TranslateRequest& request, ::translate::TranslateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::translate::TranslateRequest, ::translate::TranslateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Translate_, context, request, response);
}

void TranslateService::Stub::async::Translate(::grpc::ClientContext* context, const ::translate::TranslateRequest* request, ::translate::TranslateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::translate::TranslateRequest, ::translate::TranslateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Translate_, context, request, response, std::move(f));
}

void TranslateService::Stub::async::Translate(::grpc::ClientContext* context, const ::translate::TranslateRequest* request, ::translate::TranslateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Translate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::translate::TranslateResponse>* TranslateService::Stub::PrepareAsyncTranslateRaw(::grpc::ClientContext* context, const ::translate::TranslateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::translate::TranslateResponse, ::translate::TranslateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Translate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::translate::TranslateResponse>* TranslateService::Stub::AsyncTranslateRaw(::grpc::ClientContext* context, const ::translate::TranslateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTranslateRaw(context, request, cq);
  result->StartCall();
  return result;
}

TranslateService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TranslateService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TranslateService::Service, ::translate::Void, ::translate::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TranslateService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::translate::Void* req,
             ::translate::Void* resp) {
               return service->LoadModel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TranslateService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TranslateService::Service, ::translate::TranslateRequest, ::translate::TranslateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TranslateService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::translate::TranslateRequest* req,
             ::translate::TranslateResponse* resp) {
               return service->Translate(ctx, req, resp);
             }, this)));
}

TranslateService::Service::~Service() {
}

::grpc::Status TranslateService::Service::LoadModel(::grpc::ServerContext* context, const ::translate::Void* request, ::translate::Void* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TranslateService::Service::Translate(::grpc::ServerContext* context, const ::translate::TranslateRequest* request, ::translate::TranslateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace translate

