// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: translate.proto
// Protobuf C++ Version: 5.29.5

#include "translate.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace translate {

inline constexpr TranslateResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TranslateResponse::TranslateResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TranslateResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TranslateResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TranslateResponseDefaultTypeInternal() {}
  union {
    TranslateResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TranslateResponseDefaultTypeInternal _TranslateResponse_default_instance_;

inline constexpr TranslateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_jp_to_en_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TranslateRequest::TranslateRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TranslateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TranslateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TranslateRequestDefaultTypeInternal() {}
  union {
    TranslateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TranslateRequestDefaultTypeInternal _TranslateRequest_default_instance_;

inline constexpr LogResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : log_content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LogResponse::LogResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LogResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogResponseDefaultTypeInternal() {}
  union {
    LogResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogResponseDefaultTypeInternal _LogResponse_default_instance_;

inline constexpr LoadModelRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : model_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LoadModelRequest::LoadModelRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LoadModelRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoadModelRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoadModelRequestDefaultTypeInternal() {}
  union {
    LoadModelRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoadModelRequestDefaultTypeInternal _LoadModelRequest_default_instance_;

inline constexpr ListModelResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : model_name_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListModelResponse::ListModelResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListModelResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListModelResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListModelResponseDefaultTypeInternal() {}
  union {
    ListModelResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListModelResponseDefaultTypeInternal _ListModelResponse_default_instance_;
}  // namespace translate
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_translate_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_translate_2eproto = nullptr;
const ::uint32_t
    TableStruct_translate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::translate::LoadModelRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::translate::LoadModelRequest, _impl_.model_name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::translate::TranslateRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::translate::TranslateRequest, _impl_.content_),
        PROTOBUF_FIELD_OFFSET(::translate::TranslateRequest, _impl_.is_jp_to_en_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::translate::TranslateResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::translate::TranslateResponse, _impl_.content_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::translate::LogResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::translate::LogResponse, _impl_.log_content_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::translate::ListModelResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::translate::ListModelResponse, _impl_.model_name_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::translate::LoadModelRequest)},
        {9, -1, -1, sizeof(::translate::TranslateRequest)},
        {19, -1, -1, sizeof(::translate::TranslateResponse)},
        {28, -1, -1, sizeof(::translate::LogResponse)},
        {37, -1, -1, sizeof(::translate::ListModelResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::translate::_LoadModelRequest_default_instance_._instance,
    &::translate::_TranslateRequest_default_instance_._instance,
    &::translate::_TranslateResponse_default_instance_._instance,
    &::translate::_LogResponse_default_instance_._instance,
    &::translate::_ListModelResponse_default_instance_._instance,
};
const char descriptor_table_protodef_translate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017translate.proto\022\ttranslate\032\033google/pro"
    "tobuf/empty.proto\"&\n\020LoadModelRequest\022\022\n"
    "\nmodel_name\030\001 \001(\t\"8\n\020TranslateRequest\022\017\n"
    "\007content\030\001 \001(\t\022\023\n\013is_jp_to_en\030\002 \001(\010\"$\n\021T"
    "ranslateResponse\022\017\n\007content\030\001 \001(\t\"\"\n\013Log"
    "Response\022\023\n\013log_content\030\001 \001(\t\"\'\n\021ListMod"
    "elResponse\022\022\n\nmodel_name\030\001 \003(\t2\334\002\n\020Trans"
    "lateService\022@\n\tLoadModel\022\033.translate.Loa"
    "dModelRequest\032\026.google.protobuf.Empty\022;\n"
    "\tFreeModel\022\026.google.protobuf.Empty\032\026.goo"
    "gle.protobuf.Empty\022H\n\tTranslate\022\033.transl"
    "ate.TranslateRequest\032\034.translate.Transla"
    "teResponse0\001\022<\n\010WatchLog\022\026.google.protob"
    "uf.Empty\032\026.translate.LogResponse0\001\022A\n\tLi"
    "stModel\022\026.google.protobuf.Empty\032\034.transl"
    "ate.ListModelResponseb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_translate_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_translate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_translate_2eproto = {
    false,
    false,
    629,
    descriptor_table_protodef_translate_2eproto,
    "translate.proto",
    &descriptor_table_translate_2eproto_once,
    descriptor_table_translate_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_translate_2eproto::offsets,
    file_level_enum_descriptors_translate_2eproto,
    file_level_service_descriptors_translate_2eproto,
};
namespace translate {
// ===================================================================

class LoadModelRequest::_Internal {
 public:
};

LoadModelRequest::LoadModelRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:translate.LoadModelRequest)
}
inline PROTOBUF_NDEBUG_INLINE LoadModelRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::translate::LoadModelRequest& from_msg)
      : model_name_(arena, from.model_name_),
        _cached_size_{0} {}

LoadModelRequest::LoadModelRequest(
    ::google::protobuf::Arena* arena,
    const LoadModelRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LoadModelRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:translate.LoadModelRequest)
}
inline PROTOBUF_NDEBUG_INLINE LoadModelRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : model_name_(arena),
        _cached_size_{0} {}

inline void LoadModelRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LoadModelRequest::~LoadModelRequest() {
  // @@protoc_insertion_point(destructor:translate.LoadModelRequest)
  SharedDtor(*this);
}
inline void LoadModelRequest::SharedDtor(MessageLite& self) {
  LoadModelRequest& this_ = static_cast<LoadModelRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.model_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* LoadModelRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LoadModelRequest(arena);
}
constexpr auto LoadModelRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(LoadModelRequest),
                                            alignof(LoadModelRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LoadModelRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LoadModelRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LoadModelRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<LoadModelRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LoadModelRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<LoadModelRequest>(), &LoadModelRequest::ByteSizeLong,
            &LoadModelRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LoadModelRequest, _impl_._cached_size_),
        false,
    },
    &LoadModelRequest::kDescriptorMethods,
    &descriptor_table_translate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LoadModelRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 45, 2> LoadModelRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::translate::LoadModelRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string model_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LoadModelRequest, _impl_.model_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string model_name = 1;
    {PROTOBUF_FIELD_OFFSET(LoadModelRequest, _impl_.model_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\12\0\0\0\0\0\0"
    "translate.LoadModelRequest"
    "model_name"
  }},
};

PROTOBUF_NOINLINE void LoadModelRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:translate.LoadModelRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.model_name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LoadModelRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LoadModelRequest& this_ = static_cast<const LoadModelRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LoadModelRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LoadModelRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:translate.LoadModelRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string model_name = 1;
          if (!this_._internal_model_name().empty()) {
            const std::string& _s = this_._internal_model_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "translate.LoadModelRequest.model_name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:translate.LoadModelRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LoadModelRequest::ByteSizeLong(const MessageLite& base) {
          const LoadModelRequest& this_ = static_cast<const LoadModelRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LoadModelRequest::ByteSizeLong() const {
          const LoadModelRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:translate.LoadModelRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string model_name = 1;
            if (!this_._internal_model_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_model_name());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LoadModelRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LoadModelRequest*>(&to_msg);
  auto& from = static_cast<const LoadModelRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:translate.LoadModelRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_model_name().empty()) {
    _this->_internal_set_model_name(from._internal_model_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoadModelRequest::CopyFrom(const LoadModelRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:translate.LoadModelRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LoadModelRequest::InternalSwap(LoadModelRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.model_name_, &other->_impl_.model_name_, arena);
}

::google::protobuf::Metadata LoadModelRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TranslateRequest::_Internal {
 public:
};

TranslateRequest::TranslateRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:translate.TranslateRequest)
}
inline PROTOBUF_NDEBUG_INLINE TranslateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::translate::TranslateRequest& from_msg)
      : content_(arena, from.content_),
        _cached_size_{0} {}

TranslateRequest::TranslateRequest(
    ::google::protobuf::Arena* arena,
    const TranslateRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TranslateRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.is_jp_to_en_ = from._impl_.is_jp_to_en_;

  // @@protoc_insertion_point(copy_constructor:translate.TranslateRequest)
}
inline PROTOBUF_NDEBUG_INLINE TranslateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        _cached_size_{0} {}

inline void TranslateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_jp_to_en_ = {};
}
TranslateRequest::~TranslateRequest() {
  // @@protoc_insertion_point(destructor:translate.TranslateRequest)
  SharedDtor(*this);
}
inline void TranslateRequest::SharedDtor(MessageLite& self) {
  TranslateRequest& this_ = static_cast<TranslateRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TranslateRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TranslateRequest(arena);
}
constexpr auto TranslateRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TranslateRequest),
                                            alignof(TranslateRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TranslateRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TranslateRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TranslateRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TranslateRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TranslateRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TranslateRequest>(), &TranslateRequest::ByteSizeLong,
            &TranslateRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_._cached_size_),
        false,
    },
    &TranslateRequest::kDescriptorMethods,
    &descriptor_table_translate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TranslateRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2> TranslateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::translate::TranslateRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool is_jp_to_en = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TranslateRequest, _impl_.is_jp_to_en_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_.is_jp_to_en_)}},
    // string content = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string content = 1;
    {PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool is_jp_to_en = 2;
    {PROTOBUF_FIELD_OFFSET(TranslateRequest, _impl_.is_jp_to_en_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\32\7\0\0\0\0\0\0"
    "translate.TranslateRequest"
    "content"
  }},
};

PROTOBUF_NOINLINE void TranslateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:translate.TranslateRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _impl_.is_jp_to_en_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TranslateRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TranslateRequest& this_ = static_cast<const TranslateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TranslateRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TranslateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:translate.TranslateRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string content = 1;
          if (!this_._internal_content().empty()) {
            const std::string& _s = this_._internal_content();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "translate.TranslateRequest.content");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool is_jp_to_en = 2;
          if (this_._internal_is_jp_to_en() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_is_jp_to_en(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:translate.TranslateRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TranslateRequest::ByteSizeLong(const MessageLite& base) {
          const TranslateRequest& this_ = static_cast<const TranslateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TranslateRequest::ByteSizeLong() const {
          const TranslateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:translate.TranslateRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string content = 1;
            if (!this_._internal_content().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_content());
            }
            // bool is_jp_to_en = 2;
            if (this_._internal_is_jp_to_en() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TranslateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TranslateRequest*>(&to_msg);
  auto& from = static_cast<const TranslateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:translate.TranslateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_is_jp_to_en() != 0) {
    _this->_impl_.is_jp_to_en_ = from._impl_.is_jp_to_en_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TranslateRequest::CopyFrom(const TranslateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:translate.TranslateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TranslateRequest::InternalSwap(TranslateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
        swap(_impl_.is_jp_to_en_, other->_impl_.is_jp_to_en_);
}

::google::protobuf::Metadata TranslateRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TranslateResponse::_Internal {
 public:
};

TranslateResponse::TranslateResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:translate.TranslateResponse)
}
inline PROTOBUF_NDEBUG_INLINE TranslateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::translate::TranslateResponse& from_msg)
      : content_(arena, from.content_),
        _cached_size_{0} {}

TranslateResponse::TranslateResponse(
    ::google::protobuf::Arena* arena,
    const TranslateResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TranslateResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:translate.TranslateResponse)
}
inline PROTOBUF_NDEBUG_INLINE TranslateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        _cached_size_{0} {}

inline void TranslateResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TranslateResponse::~TranslateResponse() {
  // @@protoc_insertion_point(destructor:translate.TranslateResponse)
  SharedDtor(*this);
}
inline void TranslateResponse::SharedDtor(MessageLite& self) {
  TranslateResponse& this_ = static_cast<TranslateResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TranslateResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TranslateResponse(arena);
}
constexpr auto TranslateResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TranslateResponse),
                                            alignof(TranslateResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TranslateResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TranslateResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TranslateResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TranslateResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TranslateResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TranslateResponse>(), &TranslateResponse::ByteSizeLong,
            &TranslateResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TranslateResponse, _impl_._cached_size_),
        false,
    },
    &TranslateResponse::kDescriptorMethods,
    &descriptor_table_translate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TranslateResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> TranslateResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::translate::TranslateResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string content = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TranslateResponse, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string content = 1;
    {PROTOBUF_FIELD_OFFSET(TranslateResponse, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\7\0\0\0\0\0\0"
    "translate.TranslateResponse"
    "content"
  }},
};

PROTOBUF_NOINLINE void TranslateResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:translate.TranslateResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TranslateResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TranslateResponse& this_ = static_cast<const TranslateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TranslateResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TranslateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:translate.TranslateResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string content = 1;
          if (!this_._internal_content().empty()) {
            const std::string& _s = this_._internal_content();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "translate.TranslateResponse.content");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:translate.TranslateResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TranslateResponse::ByteSizeLong(const MessageLite& base) {
          const TranslateResponse& this_ = static_cast<const TranslateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TranslateResponse::ByteSizeLong() const {
          const TranslateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:translate.TranslateResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string content = 1;
            if (!this_._internal_content().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_content());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TranslateResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TranslateResponse*>(&to_msg);
  auto& from = static_cast<const TranslateResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:translate.TranslateResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TranslateResponse::CopyFrom(const TranslateResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:translate.TranslateResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TranslateResponse::InternalSwap(TranslateResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
}

::google::protobuf::Metadata TranslateResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LogResponse::_Internal {
 public:
};

LogResponse::LogResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:translate.LogResponse)
}
inline PROTOBUF_NDEBUG_INLINE LogResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::translate::LogResponse& from_msg)
      : log_content_(arena, from.log_content_),
        _cached_size_{0} {}

LogResponse::LogResponse(
    ::google::protobuf::Arena* arena,
    const LogResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LogResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:translate.LogResponse)
}
inline PROTOBUF_NDEBUG_INLINE LogResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : log_content_(arena),
        _cached_size_{0} {}

inline void LogResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LogResponse::~LogResponse() {
  // @@protoc_insertion_point(destructor:translate.LogResponse)
  SharedDtor(*this);
}
inline void LogResponse::SharedDtor(MessageLite& self) {
  LogResponse& this_ = static_cast<LogResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.log_content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* LogResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LogResponse(arena);
}
constexpr auto LogResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(LogResponse),
                                            alignof(LogResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LogResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LogResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LogResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<LogResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LogResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<LogResponse>(), &LogResponse::ByteSizeLong,
            &LogResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LogResponse, _impl_._cached_size_),
        false,
    },
    &LogResponse::kDescriptorMethods,
    &descriptor_table_translate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LogResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> LogResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::translate::LogResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string log_content = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LogResponse, _impl_.log_content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string log_content = 1;
    {PROTOBUF_FIELD_OFFSET(LogResponse, _impl_.log_content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\13\0\0\0\0\0\0"
    "translate.LogResponse"
    "log_content"
  }},
};

PROTOBUF_NOINLINE void LogResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:translate.LogResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.log_content_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LogResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LogResponse& this_ = static_cast<const LogResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LogResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LogResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:translate.LogResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string log_content = 1;
          if (!this_._internal_log_content().empty()) {
            const std::string& _s = this_._internal_log_content();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "translate.LogResponse.log_content");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:translate.LogResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LogResponse::ByteSizeLong(const MessageLite& base) {
          const LogResponse& this_ = static_cast<const LogResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LogResponse::ByteSizeLong() const {
          const LogResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:translate.LogResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string log_content = 1;
            if (!this_._internal_log_content().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_log_content());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LogResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LogResponse*>(&to_msg);
  auto& from = static_cast<const LogResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:translate.LogResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_log_content().empty()) {
    _this->_internal_set_log_content(from._internal_log_content());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LogResponse::CopyFrom(const LogResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:translate.LogResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LogResponse::InternalSwap(LogResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.log_content_, &other->_impl_.log_content_, arena);
}

::google::protobuf::Metadata LogResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListModelResponse::_Internal {
 public:
};

ListModelResponse::ListModelResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:translate.ListModelResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListModelResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::translate::ListModelResponse& from_msg)
      : model_name_{visibility, arena, from.model_name_},
        _cached_size_{0} {}

ListModelResponse::ListModelResponse(
    ::google::protobuf::Arena* arena,
    const ListModelResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListModelResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:translate.ListModelResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListModelResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : model_name_{visibility, arena},
        _cached_size_{0} {}

inline void ListModelResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListModelResponse::~ListModelResponse() {
  // @@protoc_insertion_point(destructor:translate.ListModelResponse)
  SharedDtor(*this);
}
inline void ListModelResponse::SharedDtor(MessageLite& self) {
  ListModelResponse& this_ = static_cast<ListModelResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ListModelResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ListModelResponse(arena);
}
constexpr auto ListModelResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ListModelResponse, _impl_.model_name_) +
          decltype(ListModelResponse::_impl_.model_name_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ListModelResponse), alignof(ListModelResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ListModelResponse::PlacementNew_,
                                 sizeof(ListModelResponse),
                                 alignof(ListModelResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ListModelResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ListModelResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ListModelResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ListModelResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ListModelResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ListModelResponse>(), &ListModelResponse::ByteSizeLong,
            &ListModelResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ListModelResponse, _impl_._cached_size_),
        false,
    },
    &ListModelResponse::kDescriptorMethods,
    &descriptor_table_translate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ListModelResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 46, 2> ListModelResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::translate::ListModelResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string model_name = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ListModelResponse, _impl_.model_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string model_name = 1;
    {PROTOBUF_FIELD_OFFSET(ListModelResponse, _impl_.model_name_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\33\12\0\0\0\0\0\0"
    "translate.ListModelResponse"
    "model_name"
  }},
};

PROTOBUF_NOINLINE void ListModelResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:translate.ListModelResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.model_name_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ListModelResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ListModelResponse& this_ = static_cast<const ListModelResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ListModelResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ListModelResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:translate.ListModelResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string model_name = 1;
          for (int i = 0, n = this_._internal_model_name_size(); i < n; ++i) {
            const auto& s = this_._internal_model_name().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "translate.ListModelResponse.model_name");
            target = stream->WriteString(1, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:translate.ListModelResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ListModelResponse::ByteSizeLong(const MessageLite& base) {
          const ListModelResponse& this_ = static_cast<const ListModelResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ListModelResponse::ByteSizeLong() const {
          const ListModelResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:translate.ListModelResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string model_name = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_model_name().size());
              for (int i = 0, n = this_._internal_model_name().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_model_name().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ListModelResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListModelResponse*>(&to_msg);
  auto& from = static_cast<const ListModelResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:translate.ListModelResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_model_name()->MergeFrom(from._internal_model_name());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListModelResponse::CopyFrom(const ListModelResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:translate.ListModelResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListModelResponse::InternalSwap(ListModelResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.model_name_.InternalSwap(&other->_impl_.model_name_);
}

::google::protobuf::Metadata ListModelResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace translate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_translate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
